/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimulacoesRouteImport } from './routes/_app.simulacoes'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppProtocolosRouteImport } from './routes/_app.protocolos'
import { Route as AppPacientesRouteImport } from './routes/_app.pacientes'
import { Route as AppExerciciosRouteImport } from './routes/_app.exercicios'
import { Route as AppEvolucoesRouteImport } from './routes/_app.evolucoes'
import { Route as AppEquipamentosRouteImport } from './routes/_app.equipamentos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulacoesRoute = AppSimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolosRoute = AppProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppExerciciosRoute = AppExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolucoesRoute = AppEvolucoesRouteImport.update({
  id: '/evolucoes',
  path: '/evolucoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosRoute = AppEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipamentos': typeof AppEquipamentosRoute
  '/evolucoes': typeof AppEvolucoesRoute
  '/exercicios': typeof AppExerciciosRoute
  '/pacientes': typeof AppPacientesRoute
  '/protocolos': typeof AppProtocolosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/simulacoes': typeof AppSimulacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipamentos': typeof AppEquipamentosRoute
  '/evolucoes': typeof AppEvolucoesRoute
  '/exercicios': typeof AppExerciciosRoute
  '/pacientes': typeof AppPacientesRoute
  '/protocolos': typeof AppProtocolosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/simulacoes': typeof AppSimulacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/equipamentos': typeof AppEquipamentosRoute
  '/_app/evolucoes': typeof AppEvolucoesRoute
  '/_app/exercicios': typeof AppExerciciosRoute
  '/_app/pacientes': typeof AppPacientesRoute
  '/_app/protocolos': typeof AppProtocolosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/simulacoes': typeof AppSimulacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/equipamentos'
    | '/evolucoes'
    | '/exercicios'
    | '/pacientes'
    | '/protocolos'
    | '/relatorios'
    | '/simulacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/equipamentos'
    | '/evolucoes'
    | '/exercicios'
    | '/pacientes'
    | '/protocolos'
    | '/relatorios'
    | '/simulacoes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/equipamentos'
    | '/_app/evolucoes'
    | '/_app/exercicios'
    | '/_app/pacientes'
    | '/_app/protocolos'
    | '/_app/relatorios'
    | '/_app/simulacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simulacoes': {
      id: '/_app/simulacoes'
      path: '/simulacoes'
      fullPath: '/simulacoes'
      preLoaderRoute: typeof AppSimulacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocolos': {
      id: '/_app/protocolos'
      path: '/protocolos'
      fullPath: '/protocolos'
      preLoaderRoute: typeof AppProtocolosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercicios': {
      id: '/_app/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof AppExerciciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evolucoes': {
      id: '/_app/evolucoes'
      path: '/evolucoes'
      fullPath: '/evolucoes'
      preLoaderRoute: typeof AppEvolucoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipamentos': {
      id: '/_app/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AppEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipamentosRoute: typeof AppEquipamentosRoute
  AppEvolucoesRoute: typeof AppEvolucoesRoute
  AppExerciciosRoute: typeof AppExerciciosRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProtocolosRoute: typeof AppProtocolosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSimulacoesRoute: typeof AppSimulacoesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipamentosRoute: AppEquipamentosRoute,
  AppEvolucoesRoute: AppEvolucoesRoute,
  AppExerciciosRoute: AppExerciciosRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProtocolosRoute: AppProtocolosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSimulacoesRoute: AppSimulacoesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
